version: "3.8"

networks:
  infra:
   ipam:
     config:
      - subnet: 10.20.1.0/16

services:
  nginx:
   image: nginx:latest
   restart: always
   ports:
    - "80:80"
    - "443:443"
   networks:
     infra: 
      ipv4_address: 10.20.1.2
   volumes:
    - /etc/localtime:/etc/locatime
    - ./default.conf:/etc/nginx/conf.d/default.conf

  
  novo-servico:
    image:  #nome da imagem que sera usada
    restart: always
    networks:
      infra:
        ipv4_address: 10.20.1.3
    ports:
      - 3060 #porta que sera usada para comunicacao com nginx
    volumes:
      - /etc/localtime:/etc/localtime
       #insira aqui o volume da aplicacao que sera usada